name = "Digital Extinction"
description = "3D real-time strategy game. A free and modern game, unconstrained by commercial requirements, legacy HW and old technology."
link = "https://github.com/DigitalExtinction/Game"
image = "digital-extinction.png"
